export enum ConversationState {
  IDLE = "IDLE",

  AI_SPEAKING = "AI_SPEAKING",

  LISTENING = "LISTENING",

  USER_SPEAKING = "USER_SPEAKING",

  WAITING = "WAITING",

  PROCESSING = "PROCESSING",
}